using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.TeleportationZone;

namespace Content.Client.TeleportationZone.UI;

[GenerateTypedNameReferences]
public sealed partial class TeleportationZoneConsoleWindow : DefaultWindow
{
    public event Action<int>? PointSelected;
    public event Action? PointsRefreshButtonPressed;
    public event Action? StartLandingButtonPressed;

    public TeleportationZoneConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        TeleportationZoneRefreshPointsButton.OnPressed += _ => PointsRefreshButtonPressed?.Invoke();
        TeleportationZoneStartLandingButton.OnPressed += _ => StartLandingButtonPressed?.Invoke();
        SubnetList.OnItemSelected += OnSubnetListSelect;
    }

    public void UpdateState(TeleportationZoneUiState state)
    {
        TeleportationZoneRefreshPointsButton.Disabled = !state.CanRefreshVol;
        TeleportationZoneStartLandingButton.Disabled = !state.CanStartVol;
        AddPointToList(state);
    }

    private void AddPointToList(TeleportationZoneUiState state)
    {
        SubnetList.Clear(); // We clean it so that there are no duplicated buttons
        foreach (var point in state.Points)
        {
            var item = SubnetList.AddItem($"{point.Value}");
            item.Metadata = point.Key; // The key contains a unique identification number (UIN), which, according to my logic, each landing point has its own
        }
    }

    private void OnSubnetListSelect(ItemList.ItemListSelectedEventArgs args)
    {
        PointSelected!((int) SubnetList[args.ItemIndex].Metadata!); // When selecting the desired object in the SubnetList, we send a unique identification number by which we will search for the desired landing point
    }
}
